CREATE DATABASE IF NOT EXISTS `myDb`;
USE `myDb`;


-- CREATE TABLE
CREATE TABLE IF NOT EXISTS APP_USER
(
  USER_ID               BIGINT NOT NULL,
  USER_NAME             VARCHAR(36) NOT NULL,
  ENCRYPTED_PASSWORD    VARCHAR(128) NOT NULL,
  ENABLED               BIT NOT NULL
);
--

ALTER TABLE APP_USER MODIFY USER_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE APP_USER ADD CONSTRAINT APP_USER_UK UNIQUE (USER_NAME);


-- CREATE TABLE
CREATE TABLE IF NOT EXISTS APP_ROLE
(
  ROLE_ID   BIGINT NOT NULL,
  ROLE_NAME VARCHAR(30) NOT NULL
);
--
ALTER TABLE APP_ROLE ADD CONSTRAINT APP_ROLE_PK PRIMARY KEY (ROLE_ID);

ALTER TABLE APP_ROLE ADD CONSTRAINT APP_ROLE_UK UNIQUE (ROLE_NAME);


-- CREATE TABLE
CREATE TABLE IF NOT EXISTS USER_ROLE
(
  ID        BIGINT NOT NULL,
  USER_ID   BIGINT NOT NULL,
  USER_NAME VARCHAR(36) NOT NULL,
  ROLE_ID   BIGINT NOT NULL
);
--

ALTER TABLE USER_ROLE MODIFY ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE USER_ROLE
  ADD CONSTRAINT USER_ROLE_UK UNIQUE (USER_NAME, ROLE_ID);

ALTER TABLE USER_ROLE
  ADD CONSTRAINT USER_ROLE_FK1 FOREIGN KEY (USER_ID)
  REFERENCES APP_USER (USER_ID);

ALTER TABLE USER_ROLE
  ADD CONSTRAINT USER_ROLE_FK2 FOREIGN KEY (ROLE_ID)
  REFERENCES APP_ROLE (ROLE_ID);


-- USED BY SPRING REMEMBER ME API.
CREATE TABLE IF NOT EXISTS PERSISTENT_LOGINS
  (
      USERNAME    VARCHAR(64) NOT NULL,
      SERIES      VARCHAR(64) NOT NULL,
      TOKEN       VARCHAR(64) NOT NULL,
      LAST_USED   TIMESTAMP NOT NULL,
      PRIMARY KEY (SERIES)
  );


  -- CREATE TABLE
  CREATE TABLE IF NOT EXISTS PRODUCT
  (
      PRODUCT_ID  BIGINT NOT NULL AUTO_INCREMENT,
      NAME        VARCHAR(64) NOT NULL,
      JOB_TITLE   VARCHAR(64) NOT NULL,
      ADDRESS     VARCHAR(64) NOT NULL,
      TELEPHONE   VARCHAR(64) NOT NULL,
      EMAIL       VARCHAR(64) NOT NULL,
      WEBSITE     VARCHAR(64) NOT NULL,
      LANGUAGE    VARCHAR(64) NOT NULL,
      ABOUT       LONGTEXT NOT NULL,
      WORK_EXPERIENCE LONGTEXT NOT NULL,
      ENABLED     BIT NOT NULL,
      USER_ID     BIGINT NOT NULL,
      PRIMARY KEY (PRODUCT_ID),
      CONSTRAINT `PRODUCT_USER_FK1` FOREIGN KEY (`USER_ID`) REFERENCES `APP_USER` (`USER_ID`)
  );

-- CREATE TABLE
  CREATE TABLE IF NOT EXISTS AVATAR
  (
      AVATAR_ID BIGINT NOT NULL AUTO_INCREMENT,
      IMAGE     BLOB NOT NULL,
      USER_ID   BIGINT NOT NULL,
      PRIMARY KEY (AVATAR_ID),
      CONSTRAINT `AVATAR_USER_FK1` FOREIGN KEY (`USER_ID`) REFERENCES `APP_USER` (`USER_ID`)
  );
